version: 2.1

jobs:
  run-codecov:
    docker:
      - image: cimg/openjdk:11.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run tests with coverage report
          command: |
            ./gradlew test
      - run:
          name: Upload the report to Codecov
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov

workflows:
  checkout-build-test:
    jobs:
      - run-codecov
