version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

  save_gradle_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

jobs:
  run-codecov:
    docker:
      - image: cimg/openjdk:11.0
    resource_class: small
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Run functional tests with coverage report
          command: |
            ./gradlew check
      - save_gradle_cache

      - codecov/upload:
          file: build/mergedReportDir/test/jacocoTestReport.xml

      - store_artifacts:
          path: build/mergedReportDir/test/jacocoTestReport.xml

workflows:
  checkout-build-test:
    jobs:
      - run-codecov
