version: 2.1

references:

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      name: Restore Gradle Cache
      keys:
        # when lock file changes, use increasingly general patterns to restore cache
        - gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
        - gradle-repo-v1-{{ .Branch }}-
        - gradle-repo-v1-

  save_gradle_cache: &save_gradle_cache
    save_cache:
      name: Save Gradle Cache
      paths:
        - ~/.gradle
      key: gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle.kts" }}


jobs:
  run-codecov:
    docker:
      - image: cimg/openjdk:11.0
    resource_class: small
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Run functional tests with coverage report
          command: |
            ./gradlew check
      - *save_gradle_cache

      - run:
          name: Upload the report to Codecov
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -f build/mergedReportDir/test/jacocoTestReport.xml

      - store_artifacts:
          path: build/mergedReportDir/test/jacocoTestReport.xml

workflows:
  checkout-build-test:
    jobs:
      - run-codecov
